// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using food_delivery.Models;

namespace food_delivery.Data
{
    public partial class ApplicationDbContext : IdentityDbContext<CustomUser>
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Dish> dishes { get; set; }
        public virtual DbSet<RestaurantDish> restaurantDishes { get; set; }
        public virtual DbSet<Restaurant> restaurants { get; set; }
        public virtual DbSet<food_delivery.Models.Type> types { get; set; }
        public virtual DbSet<RestaurantType> restaurantTypes { get; set; }
        public virtual DbSet<Zone> zones { get; set; }
        public virtual DbSet<CustomUser> CustomUsers { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ReservationStatus> ReservationStatuses { get; set; }
        public virtual DbSet<UserRestaurant> UserRestaurants { get; set; }
        public virtual DbSet<UserRestaurantDish> UserRestaurantDishes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Dish>(entity =>
            {
                entity.ToTable("dish");

                entity.HasIndex(e => e.TypeId, "ifk_DishType");

                entity.Property(e => e.Description)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.type)
                    .WithMany(p => p.dishes)
                    .HasForeignKey(d => d.TypeId)
                    .HasConstraintName("fk_type");

                entity.HasMany(m => m.restaurants)
                .WithMany(p => p.Dishes).UsingEntity<RestaurantDish>(

                    j => j.HasOne(e => e.restaurant).WithMany(),
                    j => j.HasOne(e => e.dish).WithMany()
                );
            });

            modelBuilder.Entity<Restaurant>(entity =>
            {
                entity.ToTable("restaurant");

                entity.HasIndex(e => e.TypeId, "ifk_restTypeRest");

                entity.HasIndex(e => e.ZoneId, "ifk_zoneRest");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RestUrl)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PhoneNumber)
                    .HasMaxLength(11)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.HasOne(d => d.Id_typeNavigation)
                    .WithMany(p => p.restaurants)
                    .HasForeignKey(d => d.TypeId)
                    .HasConstraintName("fk_typeRest");

                entity.HasOne(d => d.Zone)
                    .WithMany(p => p.restaurants)
                    .HasForeignKey(d => d.ZoneId)
                    .HasConstraintName("fk_zone");
            });

            modelBuilder.Entity<Models.Type>(entity =>
            {
                entity.ToTable("type");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<RestaurantType>(entity =>
            {
                entity.ToTable("restaurantType");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Zone>(entity =>
            {
                entity.HasKey(e => e.ZoneId)
                    .HasName("PK__zone__CD7EA2967C6981B9");

                entity.ToTable("zone");

                entity.Property(e => e.Description)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<RestaurantDish>(entity =>
            {
            entity.HasMany(l => l.listUsers)
            .WithMany(p => p.dishes).UsingEntity<UserRestaurantDish>(
                    j => j.HasOne(u => u.customUser).WithMany(),
                    j => j.HasOne(c => c.restaurantDish).WithMany()
                    );
            }); // Customize the CustomUser table
            modelBuilder.Entity<CustomUser>(e =>
            {
                e.ToTable(nameof(CustomUser));
                e.Property(p => p.FirstName).HasMaxLength(25);
                e.Property(p => p.LastName).HasMaxLength(50);
                e.Property(p => p.IsActive).HasDefaultValue(true);
                e.Property(p => p.PhoneNumber).HasMaxLength(11);

                e.HasMany(r => r.restaurants)
                .WithMany(u => u.Users)
                .UsingEntity<UserRestaurant>(
                    j => j.HasOne(r => r.restaurant).WithMany(),
                    j => j.HasOne(c => c.customUser).WithMany()
                );
            });

            modelBuilder.Entity<Reservation>(entity =>
            {
                entity.HasOne(c => c.CustomUser)
                .WithMany(r => r.reservations)
                .HasForeignKey(e => e.CustomerUserId)
                .HasConstraintName("fk_user_reservations");

                entity.HasOne(e => e.status)
                .WithMany(r => r.listReservations)
                .HasForeignKey(e => e.ReservationStatusId)
                .HasConstraintName("fk_status_reservation");

                entity.HasOne(r => r.restaurant)
                .WithMany(r => r.Reservations)
                .HasForeignKey(e => e.RestaurantId)
                .HasConstraintName("fk_reservation_restaurant");
            }); // Seeders
            List<IdentityRole> roles = new List<IdentityRole>
            {
                new IdentityRole { Name = "Default", NormalizedName = "DEFAULT" },
                new IdentityRole { Name = "Manager", NormalizedName = "MANAGER" },
                new IdentityRole { Name = "Admin", NormalizedName = "ADMIN" }
            };
            modelBuilder.Entity<IdentityRole>().HasData(roles);

            List<CustomUser> users = new List<CustomUser>
            {
                new CustomUser // ADMIN
                {
                    FirstName = "mahmoud",
                    LastName = "saber Attia",
                    PhoneNumber = "01001048371",
                    IsActive = true,
                    UserName = "Admin@example.com",
                    NormalizedUserName = "ADMIN@EXAMPLE.COM",
                    Email = "Admin@example.com",
                    NormalizedEmail = "ADMIN@EXAMPLE.COM",
                    EmailConfirmed = true,
                },
                new CustomUser // MANAGER
                {
                    FirstName = "Manager",
                    LastName = "motaz",
                    PhoneNumber = "01258971201",
                    IsActive = true,
                    UserName = "Manager@example.com",
                    NormalizedUserName = "MANAGER@EXAMPLE.COM",
                    Email = "Manager@example.com",
                    NormalizedEmail = "MANAGER@EXAMPLE.COM",
                    EmailConfirmed = true,
                }, new CustomUser // DEFAULT
                {
                    FirstName = "User",
                    LastName = "Abdo",
                    PhoneNumber = "0112583610",
                    IsActive = true,
                    UserName = "User@example.com",
                    NormalizedUserName = "USER@EXAMPLE.COM",
                    Email = "User@example.com",
                    NormalizedEmail = "USER@EXAMPLE.COM",
                    EmailConfirmed = true,
                },
                
            }; 
            modelBuilder.Entity<CustomUser>().HasData(users);
            var passwordHasher = new PasswordHasher<CustomUser>();
            users[0].PasswordHash = passwordHasher.HashPassword(users[0], "Saber_58");
            users[1].PasswordHash = passwordHasher.HashPassword(users[1], "1234");
            users[2].PasswordHash = passwordHasher.HashPassword(users[2], "1234");

            List<IdentityUserRole<string>> userRoles = new List<IdentityUserRole<string>>
            {
                new IdentityUserRole<string>
                {
                    RoleId = roles.Find(r => r.Name == "Admin").Id,
                    UserId = users[0].Id
                },
                new IdentityUserRole<string>
                {
                    RoleId = roles.Find(r => r.Name == "Manager").Id,
                    UserId = users[1].Id
                },
                new IdentityUserRole<string>
                {
                    RoleId = roles.Find(r => r.Name == "Default").Id,
                    UserId = users[2].Id
                },
               
            }; 
            modelBuilder.Entity<IdentityUserRole<string>>().HasData(userRoles);

            List<ReservationStatus> statuses = new List<ReservationStatus>
            {
                new ReservationStatus { Id = -1, Name = "Active" },
                new ReservationStatus { Id = -2, Name = "Pending" },
                new ReservationStatus { Id = -3, Name = "Cancelled" },
                new ReservationStatus { Id = -4, Name = "Rejected" },
                new ReservationStatus { Id = -5, Name = "Completed" }
            };

            modelBuilder.Entity<ReservationStatus>().HasData(statuses);

            base.OnModelCreating(modelBuilder);
        }

        //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}