// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using food_delivery.Models;
using System.ComponentModel.DataAnnotations;

namespace food_delivery.Models
{
    public partial class RestaurantDish
    {

        [Key]
        public int Id { get; set; }
        public int DishId { get; set; }
        public int RestaurantId { get; set; }

        [Range(1, 5, ErrorMessage = "The rating must be between 1 and 5")]
        public int Rating { get; set; }
        public bool IsActive { get; set; }

        public virtual Dish dish { get; set; }
        public virtual Restaurant restaurant { get; set; }
        public virtual ICollection<CustomUser> listUsers { get; set; }

        public ICollection<DishRating> Ratings { get; set; }

        public RestaurantDish()
        {
            this.listUsers = new HashSet<CustomUser>();
        }
    }
}
