// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using food_delivery.Models;
using System;
using System.Collections.Generic;

namespace food_delivery.Models
{
    public partial class UserRestaurant
    {
        public int id { get; set; }
        public string UserId { get; set; }
        public int RestaurantId { get; set; }

        public virtual Restaurant restaurant { get; set; }

        public virtual CustomUser customUser { get; set; }
    }
}