// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using food_delivery.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace food_delivery.Models
{
    public partial class Zone
    {
        public Zone()
        {
            restaurants = new HashSet<Restaurant>();
        }

        public int ZoneId { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "The 'Name' field is required")]
        public string Name { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "The 'Description' field is required")]
        public string Description { get; set; }

        public string ImageURL { get; set; }

        public virtual ICollection<Restaurant> restaurants { get; set; }
    }
}